# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4c8a808c35fba67a236b2634d9006d57471147fe035debe3c913b24e7550a402f514ed735487f56852890809286f2d56ec433ddea8ca223de2cf7181f22acc

test:
  secret_key_base: 1593fc3a6df746070fd7b8bf3b20268c06bb0364ae631657d1b693442b4533fe3377fb191885901da8d8d577bdd32ad42334f143307bd9358d98bddfabb9efa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
